FROM openjdk:11-jre-slim-stretch 
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
RUN useradd -m myuser
USER myuser
EXPOSE 8080
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=prod","/app.jar"]
